
# tap repositories and their packages

tap homebrew/cask
cask google-chrome
cask iterm2
cask visual-studio-code
cask karabiner-elements
cask slack
cask alfred
cask authy
cask dropbox
cask google-japanese-ime
cask google-cloud-sdk


tap homebrew/core
brew x264
brew gdbm
brew pcre
brew lame
brew ghq
brew pyenv
brew coreutils
brew direnv
brew xvid
brew tig
brew readline
brew peco
brew ffmpeg
brew rbenv
brew openssl
brew autoconf
brew ruby-build
brew pkg-config
brew awscli

tap rcmdnk/file

# App Store applications
appstore 443987910 1Password (6.8.2)
appstore 417375580 BetterSnapTool (1.7)
